services:
  # 現有的應用服務
#  crm-agent:
#    build: .
#    ports:
#      - "8000:8000"
#    environment:
#      - MILVUS_HOST=milvus-standalone
#      - MILVUS_PORT=19530
#      - POSTGRES_URI=${POSTGRES_URI}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#    depends_on:
#      - milvus-standalone
#      - etcd
#      - minio
#    volumes:
#      - ./dummy_data:/app/dummy_data
#    networks:
#      - milvus

  # Milvus standalone
  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - milvus

  # etcd
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - milvus

  # MinIO
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    command: minio server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  # Attu - Milvus 管理界面 (可選)
  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.3.0
    environment:
      MILVUS_URL: milvus-standalone:19530
    ports:
      - "3000:3000"
    depends_on:
      - milvus-standalone
    networks:
      - milvus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    env_file:
      - .env
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # Jaeger UI
      - "4318:4318"     # OTLP HTTP (default for OpenTelemetry)
    restart: unless-stopped
    networks:
      - milvus

networks:
  milvus:
    driver: bridge

volumes:
  milvus_data:
  etcd_data:
  minio_data:
